# write a program to input eight numbers from the user and display all the unique number(once).
s = set()
n = input("enter the number: ")
s.add(int(n))
n = input("enter the number: ")
s.add(int(n))
n = input("enter the number: ")
s.add(int(n))
n = input("enter the number: ")
s.add(int(n))
n = input("enter the number: ")
s.add(int(n))
n = input("enter the number: ")
s.add(int(n))
n = input("enter the number: ")
s.add(int(n))
n = input("enter the number: ")
s.add(int(n))
print(s)


